
### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
import torch

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:

# Create random tensor
tensor = torch.rand(size=(7,7))
tensor

tensor([[0.4273, 0.4802, 0.8653, 0.5180, 0.9920, 0.8593, 0.7378],
        [0.7563, 0.9933, 0.9729, 0.1486, 0.5952, 0.3671, 0.1648],
        [0.4628, 0.7687, 0.9915, 0.2909, 0.5565, 0.8122, 0.2288],
        [0.5422, 0.4949, 0.0389, 0.6004, 0.3699, 0.0909, 0.5760],
        [0.2703, 0.2954, 0.3047, 0.0176, 0.8114, 0.1367, 0.9402],
        [0.9718, 0.2259, 0.7039, 0.3289, 0.0596, 0.0447, 0.3034],
        [0.8173, 0.0189, 0.3746, 0.8431, 0.4543, 0.0133, 0.5204]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
maxtrix_tensor = torch.rand(size=(1,7))
# Perform matrix multiplication 
matxrix_multiply = torch.matmul(tensor,maxtrix_tensor.T)
matxrix_multiply

tensor([[2.6718],
        [2.3732],
        [2.1402],
        [1.4427],
        [1.9609],
        [1.6089],
        [1.7246]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [35]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random = torch.rand(size=(7,7))
random_1 = torch.rand(size=(1,7))
# Matrix multiply tensors
# torch.matmul(maxtrix_tensor)
print(torch.matmul(input = random,other=random_1.T),torch.matmul(input = random,other=random_1.T).size())

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [38]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [48]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    print("cuda is  available")
else:
    print(" using CPU ")
# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3),device=None)
tensor_B  = torch.rand(size=(2,3),device=None)
print(tensor_A)
print( tensor_B)

 using CPU 
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [55]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A,tensor_B.T)
tensor_C 

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [57]:
# Find max
print(tensor_C.max())
# Find min
print(tensor_C.min())

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [59]:
# Find arg max
print(tensor_C.argmax())

# Find arg min
print(tensor_C.argmin())

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [6]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1,1,1,10))


# Remove single dimensions
random_tensor_1  = random_tensor.squeeze()

# Print out tensors and their shapes
print(random_tensor,random_tensor.shape)
print( )
print(random_tensor_1,random_tensor_1.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
