In [68]:
!nvidia-smi

Sun Mar 24 17:06:05 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0              28W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [69]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [70]:
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

## Creating tensors

In [71]:
## scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [72]:
scalar.dtype

torch.int64

In [73]:
scalar.ndim

0

In [74]:
# get tensor back as Python int
scalar.item()

7

In [75]:
## vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [76]:
vector.ndim

1

In [77]:
vector.shape

torch.Size([2])

In [78]:
## MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [79]:
MATRIX.ndim

2

In [80]:
MATRIX.shape

torch.Size([2, 2])

In [81]:
MATRIX[0]

tensor([7, 8])

In [82]:
MATRIX[1]

tensor([ 9, 10])

In [83]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [3,6,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [3, 6, 9]]])

In [84]:
TENSOR.ndim

3

In [85]:
TENSOR.shape

torch.Size([1, 3, 3])

In [86]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 6, 9]])

In [87]:
TENSOR[0][1]

tensor([4, 5, 6])

In [88]:
## TENSOR
TENSOR = torch.tensor([[[[1,2,3],
                        [4,5,6],
                        [3,6,9],
                         [1,6,8]]]])
TENSOR


tensor([[[[1, 2, 3],
          [4, 5, 6],
          [3, 6, 9],
          [1, 6, 8]]]])

In [89]:
TENSOR.ndim

4

In [90]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

## Random Tensors

In [91]:
## Create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))   # here if we can't use size attribute also we can get (3,4) size tensor
random_tensor

tensor([[0.0523, 0.8847, 0.2497, 0.5988],
        [0.4175, 0.6499, 0.3111, 0.3931],
        [0.3492, 0.8939, 0.2794, 0.2100]])

In [92]:
## Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9528, 0.5468, 0.9622, 0.6269],
        [0.2642, 0.9174, 0.5473, 0.1164],
        [0.5021, 0.9312, 0.6171, 0.3056]])

In [93]:
random_tensor.ndim

2

In [94]:
## create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height , width ,colour channels ( R,G,B)
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [95]:
random_image_size_tensor.ndim

3

## Zeros and Ones

In [96]:
## Create a tensor of alll zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [97]:
zeros**random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [98]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
ones.dtype

torch.float32

In [100]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors -like

In [101]:
## use torch.arrange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
one_to_100 = torch.arange(start=1,end=100,step=5)
one_to_100

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [103]:
## Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_100)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data types

In [104]:
## Float 32 tensor
float_32_tensor = torch.tensor([3.0,9.0,7.0],dtype = None)
float_32_tensor

tensor([3., 9., 7.])

In [105]:
## Float 32 tensor
float_32_tensor = torch.tensor([3.0,9.0,7.0]
                               ,dtype = None,# what datatype is the tensor eg:- float32,float16
                               device =None,# what device is your tensor on
                               requires_grad=False)#whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 9., 7.])

In [106]:
float_16_tensor  = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 9., 7.], dtype=torch.float16)

In [107]:
float_16_tensor*float_32_tensor

tensor([ 9., 81., 49.])

In [108]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [109]:
int_32_tensor*float_32_tensor

tensor([ 9., 54., 63.])

In [110]:
int_64_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_64_tensor

tensor([3, 6, 9])

In [111]:
float_16_tensor*int_64_tensor

tensor([ 9., 54., 63.], dtype=torch.float16)

## getting information from tensors(tensors attributes)
1.Tensors not right datatypes-to do get datatypes from tensors ,can use`tensor.dtype`

2.Tensors not right shape- to do get Shape from tensors ,can use`tensor.shape`

3.Tensors not on the right devices-to do get device from tensors ,can use`tensor.device`

In [112]:
## create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3818, 0.9808, 0.4693, 0.8114],
        [0.3851, 0.3002, 0.8823, 0.6216],
        [0.2667, 0.9329, 0.0256, 0.4201]])

In [113]:
some_tensor.size()

torch.Size([3, 4])

In [114]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [115]:
# find out details about some tensor
print(some_tensor)
print(f"datatype of tensor :",{some_tensor.dtype})
print(f"shape of tensor :",{some_tensor.shape})
print(f"device of tensor :",{some_tensor.device})

tensor([[0.3818, 0.9808, 0.4693, 0.8114],
        [0.3851, 0.3002, 0.8823, 0.6216],
        [0.2667, 0.9329, 0.0256, 0.4201]])
datatype of tensor : {torch.float32}
shape of tensor : {torch.Size([3, 4])}
device of tensor : {device(type='cpu')}


### Manipulating Tensors(tensors operations)
Tensor operations include:-

Addition

Subtraction

Multiplication(element-wise)

Division

Matrix Multiplication (here dot product is used)



In [116]:
## Create a tensor addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [117]:
## Multiply tensor
tensor_mulitply = torch.tensor([5,6,7])
tensor_mulitply*tensor

tensor([ 5, 12, 21])

In [118]:
## Substraction tensor
tensor_substract = torch.tensor([23,45,67])
tensor_substract-tensor

tensor([22, 43, 64])

In [119]:
## division tensor
tensor_division = torch.tensor([15,25,35])
tensor_division/tensor

tensor([15.0000, 12.5000, 11.6667])

In [120]:
## Pytorch in built functions
torch.mul(tensor,10)  # mulitplcation by element wise

tensor([10, 20, 30])

In [121]:
# addition function using
torch.add(tensor,112)

tensor([113, 114, 115])

In [122]:
output_tensor = torch.add(input=tensor, alpha=10,other =20)
output_tensor ## addition function using all attributes

tensor([201, 202, 203])

##  Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning

1.Element-wise Multiplication

2.Matrix multiplication (dot product)

There are two main rules that performing Matrix multiplication needs to satsify:

1.The `*inner dimensions*` must match :    
*`(3,2) @ (3,2)` -> won't work

*`(2,3) @ (3,2)` -> will work

*`(3,2)  @ (2,3)` will work

2.The resulting matrix has the shape of `*Outer dimensions*`

*`(2,3) @ (3,2)` -> (2,2)

*`(3,2) @ (2,3)` -> (3,3)

In [123]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [124]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [125]:
%%time
value = 0
for i in range(len(tensor)):
  value +=  tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 2.62 ms


In [126]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 36 µs, sys: 0 ns, total: 36 µs
Wall time: 38.4 µs


tensor(14)

In [127]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4817, 0.7412, 0.5967],
        [0.5742, 0.7975, 0.6071],
        [0.6420, 0.6789, 0.4210]])

In [128]:
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[2.9544, 2.8749, 3.4796],
        [2.1235, 1.6608, 2.0444],
        [2.2046, 1.6672, 2.3993]])

In [129]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [130]:
# torch.matmul(torch.rand(10,10),torch.rand(7,10)) # This matrix shape is not same

## One of the most common errors in deep learning : shape errors

In [131]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm is the same as torch.matmul(it is a an alias for writing less code)
# torch.mm(tensor_A,tensor_B)
print(tensor_A.shape,tensor_B.shape)

torch.Size([3, 2]) torch.Size([3, 2])


In [132]:
## to fix the tensor shape issue we can manipulate the shape of one of the tensor using  transpose.
## A transpose switches the axis or dimensions of a given tensor.

In [133]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [134]:
# The matrix multiplication operation work when any one matix sholud be transpose
print(f"original shapes :tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.shape}")
print(f"New shape : tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.T.shape}")
print(f"Multiply :{tensor_A.shape} @ {tensor_B.T.shape}--> inner dimensions must match")
print("output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape :{output.shape}")

original shapes :tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([3, 2])
New shape : tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([2, 3])
Multiply :torch.Size([3, 2]) @ torch.Size([2, 3])--> inner dimensions must match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape :torch.Size([3, 3])


In [135]:
tensor_A @ tensor_B.T # by this also we can perform  matrix  multiplication

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min ,max,mean,sum etc (Tensor aggregation)

In [136]:
## creating a tensor
a = torch.arange(4,90,5)
a , a.dtype

(tensor([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89]),
 torch.int64)

In [137]:
#finding min
torch.min(a) , a.min()

(tensor(4), tensor(4))

In [138]:
#finding min
torch.max(a) , a.max()

(tensor(89), tensor(89))

In [139]:
## mean function required a tensor is float or complex
torch.mean(a.type(torch.float32))   , a.type(torch.float32).mean()

(tensor(46.5000), tensor(46.5000))

In [140]:
# finding sum
a.sum() ,torch.sum(a)

(tensor(837), tensor(837))

## Finding the positonal min and max

In [141]:
a

tensor([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89])

In [142]:
# find the position of tensor that has minimum value and return minimum value index
a.argmin()

tensor(0)

In [143]:
# find the position of tensor that has max value and return max value index
a.argmax()

tensor(17)

In [144]:
a[17]

tensor(89)

## reshaping  stacking ,squeezing ,unsqueezing tensors
* Reshaping - reshape an input tensor to defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each others (vstack) or side by side (hstack)
*  squeeze - removes all `1` dimensions from a tensor
*  unsqueeze - add all `1` dimensions target a tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [145]:
#  create a tensor
x = torch.arange(1.,11.)
x ,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [146]:
# add extract dimension
x_reshape = x.reshape(5,2)
x_reshape , x_reshape.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [147]:
## changing  a view
z= x.view(1,10)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [148]:
## changing z  change x(because a view of a tensor shares the same memory as the original input )
z[:,0] =5
print(f"z = {z}")
print(f"x = {x}")

z = tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
x = tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [149]:
# stack  tensors on top  of each other
x_stack = torch.stack([x,x,x,x],dim=0) # horizonatl stacking
x_stack

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [150]:
# stack  tensors on top  of each other
x_stack = torch.stack([x,x,x,x],dim=1) # vertical stacking
x_stack

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [151]:
## squeeze
x_squueze = x_reshape.reshape(1,10)
x_squueze,x_squueze.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [152]:
print(f"Previous x_reshape:,{x_squueze}")
print(f"Previous x_reshape:,{x_squueze.shape}")
# remove rextact dimension
x_squuezed = x_squueze.squeeze()
print(f"\n New tensor :",{x_squuezed})
print(f" New shape :",{x_squuezed.shape})

Previous x_reshape:,tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous x_reshape:,torch.Size([1, 10])

 New tensor : {tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])}
 New shape : {torch.Size([10])}


In [153]:
# unsqueeze()
print(f"Previous x_reshape:,{x_squueze}")
print(f"Previous x_reshape:,{x_squueze.shape}")
# add rextact dimension
x_unsquuezed = x_squueze.unsqueeze(dim=0)
print(f"\n New tensor :",{x_squuezed})
print(f" New shape :",{x_unsquuezed.shape})
print(f"dimension of tensor {x_unsquuezed.ndim}")

Previous x_reshape:,tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous x_reshape:,torch.Size([1, 10])

 New tensor : {tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])}
 New shape : {torch.Size([1, 1, 10])}
dimension of tensor 3


In [154]:
# permute()
z_original = torch.rand(size=(224,224,3)) #[height ,width,colour_channels]
# permute the original tensor to rearrange the axis or dim order
z_permute = z_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f" Previous shape :",{z_original.shape})   #[height ,width,colour_channels]
print(f"New shape {z_permute.shape}") # colour_channel,height ,width,]

 Previous shape : {torch.Size([224, 224, 3])}
New shape torch.Size([3, 224, 224])


In [155]:
z_original[0,0,0] = 2347

In [156]:
z_original[0,0,0] ,  z_permute[0,0,0]

(tensor(2347.), tensor(2347.))

## Indexing (selecting data from tensors)
* Indexing with Pytorch is similar to indexing with numpy

In [157]:
# create a tensor
y = torch.arange(1,10).reshape(1,3,3)
y  , y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [158]:
# index a new tensor
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [159]:
# index a middle bracket (dim=1) tensor
y[0][0]

tensor([1, 2, 3])

In [160]:
# index a most inner bracket (last dimension) tensor
y[0][0][1]

tensor(2)

In [161]:
y[0][2][2]

tensor(9)

In [162]:
# we can also use : to select all taregt dimension
y[:,0]

tensor([[1, 2, 3]])

In [163]:
# get all values of 0 th and 1st dimension but only index 1 and 2nd dimension
y[:,:,1]

tensor([[2, 5, 8]])

In [164]:
# get all values of 0 th  dimension but only 1  index  value of 1st  and 2nd dimension
y[:,1,1]

tensor([5])

In [165]:
#fet index 0 of 0 th and 1st dimension and all value of 2nd dimension
y[0,0,:]

tensor([1, 2, 3])

In [166]:
# index of return 9
y[:,2,2]

tensor([9])

In [167]:
# index of return 3,6,9
y[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & Numpy
* Numpy is a popular scientific Python Numerical computing library.

And  because of this Pythorch has functionality to interact with it.
* Data in Numpy want in pytorch tensor -> `torch.from_numpy(ndarray)`.
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`.

In [168]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch  , pytorch reflects numpy's default datatype of float64 until we specific datatype to tensor
array  , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [169]:
array.dtype , tensor.dtype

(dtype('float64'), torch.float64)

In [170]:
ndarray = np.arange(1.0,8.0)
tensor = torch.from_numpy(ndarray)
ndarray  , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [171]:
# change the value of arrya what will tensor to do
ndarray = ndarray + 1
ndarray , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [172]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [173]:
 numpy_tensor.dtype

dtype('float32')

In [174]:
# change the tensor what happens to numpy_tensor
tensor = tensor + 1
tensor ,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random outof random)
* In short how a neural networks learns:-

* Start with random numbers--> tensor operations --> update random numbers to try and make them better representations of data --> again --> again -->again ..

* To reduce the randomness in neural networks and Pytorch comes the conceptx of ***random seeds***.
* Essentially what the random seed does is "flavour" the randomness.

In [175]:
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8060, 0.1950, 0.5281, 0.7278],
        [0.3097, 0.4950, 0.9353, 0.2126],
        [0.3818, 0.7317, 0.8988, 0.2262]])
tensor([[0.2679, 0.8295, 0.4533, 0.4359],
        [0.5110, 0.3842, 0.2556, 0.5552],
        [0.7169, 0.5403, 0.2462, 0.5831]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [176]:
# let's make some random but reproducible tensors
# set random sedd
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and Pytorch objects on the GPUs (and Making faster computations)

GPUs = Faster computation on numbers , thanks to CUDA+NVIDIA hardware+ Pytorch working behind the scenes to make everything good

## 1. Getting a GPU
1. Easy - use google colab for free GPU (option to upgrade as well).
2.Use your own GPU - takes a little bit of setup and requires the investemnts of purchasing a GPU .
3. Use cloud computing - GCP,AWS,Azure these services allow you to rent computers on the cloud and access them.

For 2,3 PyTorch + GPU drivers(CUDA) take a little bit of setting up,to do this refer Pytorch setup documentation

In [177]:
!nvidia-smi

Sun Mar 24 17:06:08 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0              28W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 2. check for GPU access with PyTorch

In [178]:
# check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [179]:
## setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [180]:
# count number of device
torch.cuda.device_count()

1

### 3.Putting  tensor and models on the GPU

The Reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [181]:
## create a tensor (deafult on cpu )
tensor = torch.tensor([1,2,3],device="cpu")

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [182]:
# move tensor to GPU (if avaliable)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4.Moving tensors back to the CPU

In [184]:
# If tensor is on GPU can't transform to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [185]:
## To fix the GPU tensor with numpy issue ,we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [186]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')